Repository googleapis/python-recommender, pull requests merged in 2020-05, with the labels that each got.

#15 docs: updates docstrings
  .kokoro/publish-docs.sh
  docs/index.rst
  docs/multiprocessing.rst
  google/cloud/recommender_v1/proto/recommendation_pb2.py
  google/cloud/recommender_v1beta1/proto/insight_pb2.py
  google/cloud/recommender_v1beta1/proto/recommender_service_pb2.py
  synth.metadata
Labels: automerge, cla: yes

#17 feat: release as production/stable
  .repo-metadata.json
  README.rst
  setup.py
Labels: cla: yes

#20 docs: update link in README
  README.rst
Labels: cla: yes

#24 chore: change docstring line breaks (via synth)
  google/cloud/recommender_v1/proto/recommendation_pb2.py
  google/cloud/recommender_v1beta1/proto/insight_pb2.py
  google/cloud/recommender_v1beta1/proto/recommender_service_pb2.py
  synth.metadata
Labels: cla: yes, context: none

#25 chore: change docstring line breaks (via synth)
  google/cloud/recommender_v1/proto/recommendation_pb2.py
  google/cloud/recommender_v1/proto/recommender_service_pb2.py
  google/cloud/recommender_v1beta1/proto/insight_pb2.py
  google/cloud/recommender_v1beta1/proto/recommendation_pb2.py
  google/cloud/recommender_v1beta1/proto/recommender_service_pb2.py
  synth.metadata
Labels: cla: yes, context: partial
