Repository googleapis/python-recommender, pull requests merged in 2021-04, with the labels that each got.

#78 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: full

#80 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: recommender, cla: yes, context: full, samples

#81 chore: prevent normalization of semver versioning
  setup.py
Labels: api: recommender, cla: yes

#83 chore(revert): revert preventing normalization
  setup.py
Labels: api: recommender, cla: yes
